[package]
name = "rope_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gms_binder = { path = "../gms_binder" }

[lib]
crate-type = ["cdylib"]